name: listenable_stream
description: Convert Listenable (e.g. ChangeNotifier), ValueListenable(e.g. ValueNotifier) to Stream / ValueStream.
version: 2.0.1
homepage: https://github.com/Flutter-Dart-Open-Source/listenable_stream.git
repository: https://github.com/Flutter-Dart-Open-Source/listenable_stream.git
issue_tracker: https://github.com/Flutter-Dart-Open-Source/listenable_stream/issues
funding:
  - https://www.buymeacoffee.com/hoc081098

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  rxdart: ^0.28.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

topics:
  - rxdart
  - hoc081098
  - reactive-programming
  - bloc
  - state-management