name: listenable_stream
description: Convert Listenable (eg. ChangeNotifier), ValueListenable(eg. ValueNotifier) to Stream / ValueStream.
version: 1.1.0
homepage: https://github.com/Flutter-Dart-Open-Source/listenable_stream.git
repository: https://github.com/Flutter-Dart-Open-Source/listenable_stream.git
issue_tracker: https://github.com/Flutter-Dart-Open-Source/listenable_stream/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  rxdart: ^0.27.3
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

flutter:
